proxyPort: 9000
proxyName: "MightyAnt"
silent: false
arbitraryMode: false
destinationUrl: "ws://localhost:7300/"
mirrorUrls:
  - "ws://localhost:7301"
  - "ws://localhost:7302"
  - "ws://localhost:7303"